name: Windows

on: [ push, pull_request ]

env:
  CCACHE_VERSION: 4.2.1
  CCACHE_DIR: ${{ github.workspace }}\src\ccache
  CCACHE_COMPRESS: true
  CCACHE_COMPRESSLEVEL: 6
  CCACHE_NLEVELS: 4

jobs:
  build:
    runs-on:
      windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d-%H;%M;%S")"
        shell: bash
      
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ env.CCACHE_DIR }}
            game\bin\tf2vintage
            src\lib\public\mathlib.lib
            src\lib\public\tier1.lib
            src\lib\public\raytrace.lib
            src\lib\public\vgui_controls.lib
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}
          restore-keys: ${{ runner.os }}-

      - name: Download ccache
        id: ccache
        shell: cmake -P {0}
        run: |
          set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v$ENV{CCACHE_VERSION}/${{ runner.os }}.tar.xz")
          file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz)
      
      - name: Setup ccache
        run: |
          ./ccache.exe --set-config cache_dir=$CCACHE_DIR
          ./ccache.exe --set-config compression_level=6
      
      - name: Configure dependencies
        uses: ilammy/msvc-dev-cmd@v1
        with:
          toolset: 14.0
          spectre: true
          arch: x86

      - name: Configure registry
        shell: powershell
        run: |
          REG ADD "HKLM\Software\Microsoft\VisualStudio\12.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}" /v "DefaultProjectExtension" /t REG_SZ  /d "vcxproj" /f /reg:32
          REG ADD "HKLM\Software\Microsoft\VisualStudio\12.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}" /v "PossibleProjectExtensions" /t REG_SZ /d "vcxproj;vcxitems;vcproj;mak" /f /reg:32

      - name: Create project
        run: cd src;devtools/bin/vpc.exe /tf2vintage /2015 +game /mksln TF2vintage.sln

      - name: Build project
        run: |
          $ProgramFiles(x86)\\Microsoft Visual C++ Build Tools\\vcbuildtools.bat
          ./ccache.exe msbuild -m src/TF2vintage.sln /t:Build /p:Configuration=Release
      
      - name: Pack
        shell: bash
        run: tar cJfv Windows.tar.xz game/tf2vintage/bin

      - name: Upload product
        uses: actions/upload-artifact@v2
        with:
          name: TF2Vintage
          path: .\
